version: '3.1'

services:

  db:
    image: postgres
    container_name: bd
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 123456789

  app:
    image: node:alpine
    container_name: app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
    volumes:
      - ..:/usr/src
    working_dir: /usr/src
    command: npm run start:dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"