version: '3.1'

services:

  db:
    image: postgres
    container_name: bd
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 123456789
